# Generated by Django 3.2.12 on 2022-04-20 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220418_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 22, 14, 30, 16, 764851, tzinfo=utc), null=True),
        ),
    ]
